"""Bulk tool registration from an OpenAPI spec — the answer to "I have 70
endpoints and only want to register 40 of them as tools."

`WeaveClient.add_tool()` (client.py) is the one-endpoint-at-a-time
primitive and stays the right choice for a handful of tools. A business
with a large existing API (dozens to hundreds of routes) shouldn't have
to write dozens of add_tool() calls by hand just to make a deliberate
in/out decision on each one — the same problem a service with hundreds of
gRPC methods runs into, solved there by generating one tool per method
from a compiled proto descriptor and filtering with an exclude-list
(see: ml-services-dev's cusp_agent, `cusp_autogenerated_mcp_server.py`'s
descriptor-driven MCP tool generation). `tools_from_openapi` is Weave's
HTTP-shaped equivalent: it reads a tenant's existing OpenAPI document (the
tenant's own descriptor of their API) and turns each selected operation
into the exact kwargs `add_tool()` expects, still with the same policy
this platform already enforces — no default that's ever "expose
everything," `visibility` is deliberate per-operation not per-spec, and
`description` is mandatory (PLAN.md's tool-description requirement) — a
spec-driven registration path is not an excuse to skip any of that.

Usage (see `WeaveClient.add_tools_from_openapi`, the async wrapper around
this pure function):

    tenant_api_spec = json.load(open("openapi.json"))
    # Register only these 40 of the API's 70 operations:
    await client.add_tools_from_openapi(
        tenant_api_spec,
        include={"track_order", "get_product_info", ...},  # 40 operationIds
    )
    # ...or the inverse — register everything except a named 30:
    await client.add_tools_from_openapi(
        tenant_api_spec,
        exclude={"delete_customer_account", "internal_debug_dump", ...},
    )
"""

from dataclasses import dataclass, field
from typing import Any

_HTTP_METHODS = {"get", "post", "put", "patch", "delete"}


class OpenApiRegistrationError(ValueError):
    """Raised when a spec can't be turned into tool-registration calls —
    e.g. an operation selected for registration has no description, or
    both `include` and `exclude` were given (ambiguous: pick one)."""


@dataclass
class PlannedTool:
    """One operation, already resolved into `WeaveClient.add_tool()`'s
    exact keyword arguments — kept as a dataclass rather than a bare dict
    so callers (and tests) get attribute access and a real type."""

    name: str
    description: str
    endpoint: str
    method: str
    params_schema: dict[str, Any] = field(default_factory=dict)
    visibility: str = "internal"
    category: str = "general"
    auth_mode: str = "none"


def _operation_id(method: str, path: str, op: dict[str, Any]) -> str:
    if op.get("operationId"):
        return op["operationId"]
    # Fallback matching cusp_autogenerated_mcp_server.py's convention
    # (snake_case, no leading punctuation) for specs that never bothered
    # to set operationId — every OpenAPI operation still gets a stable,
    # readable tool name even then.
    slug = path.strip("/").replace("/", "_").replace("{", "").replace("}", "")
    return f"{method}_{slug}" if slug else method


def _params_schema(parameters: list[dict[str, Any]]) -> dict[str, Any]:
    properties: dict[str, Any] = {}
    required: list[str] = []
    for p in parameters:
        if p.get("in") not in ("path", "query"):
            continue  # header/cookie params aren't part of this schema shape
        schema = p.get("schema") or {}
        properties[p["name"]] = {
            "type": schema.get("type", "string"),
            "description": p.get("description", ""),
        }
        if p.get("required") or p.get("in") == "path":  # OpenAPI requires all path params
            required.append(p["name"])
    result: dict[str, Any] = {"type": "object", "properties": properties}
    if required:
        result["required"] = required
    return result


def _base_url(spec: dict[str, Any]) -> str:
    servers = spec.get("servers") or []
    if servers and servers[0].get("url"):
        return servers[0]["url"].rstrip("/")
    return ""


def tools_from_openapi(
    spec: dict[str, Any],
    *,
    base_url: str | None = None,
    include: set[str] | list[str] | None = None,
    exclude: set[str] | list[str] | None = None,
    default_visibility: str = "internal",
    default_category: str = "general",
    default_auth_mode: str = "none",
) -> list[PlannedTool]:
    """Resolves an OpenAPI 3.x document into the list of tools to
    register — the selection/validation logic, with no network or core
    RPC calls (see `WeaveClient.add_tools_from_openapi` for the async
    wrapper that actually calls `add_tool()` per result). Kept pure and
    synchronous specifically so it's cheaply unit-testable without a core
    connection.

    include/exclude are operationId sets — mutually exclusive (pass at
    most one): `include` registers ONLY those operationIds (the "pick 40
    of my 70" case), `exclude` registers every operation EXCEPT those
    (the "register everything except these 30" case). Passing neither
    registers every operation in the spec, which is rarely what a real
    integrator with a large API wants — most callers should pass one.

    Per-operation visibility/category/auth_mode default to
    `default_visibility`/`default_category`/`default_auth_mode` but can
    be overridden per operation via the `x-weave-visibility` /
    `x-weave-category` / `x-weave-auth-mode` OpenAPI extension keys, e.g.
    `{"get": {..., "x-weave-visibility": "external", "x-weave-auth-mode":
    "user_token"}}` — the same per-tool decision
    `add_tool(visibility=..., category=..., auth_mode=...)` makes
    explicit for a hand-written call, expressible directly in the spec
    for a bulk one. A "user_token" operation still needs a credential to
    sign with (`WeaveClient.add_tools_from_openapi`'s `credential_secret`
    — core rejects "user_token" with none set, same as `add_tool()`).

    Raises OpenApiRegistrationError if both include and exclude are
    given, or if any operation selected for registration has no
    `description`/`summary` — the same non-negotiable rule `core`
    enforces at manifest-refresh time (docs/architecture/ARCHITECTURE.md
    §3's "Tool descriptions are mandatory"), surfaced here at
    registration time instead of a later, harder-to-trace core rejection.
    """
    if include is not None and exclude is not None:
        raise OpenApiRegistrationError(
            "pass at most one of include/exclude, not both — 'include' means "
            "\"register only these operationIds\", 'exclude' means \"register "
            "everything except these\"; combining them is ambiguous"
        )
    include_set = set(include) if include is not None else None
    exclude_set = set(exclude) if exclude is not None else set()

    resolved_base = base_url if base_url is not None else _base_url(spec)

    planned: list[PlannedTool] = []
    for path, path_item in (spec.get("paths") or {}).items():
        for method, op in path_item.items():
            if method.lower() not in _HTTP_METHODS:
                continue  # e.g. "parameters" shared across all methods on this path

            op_id = _operation_id(method, path, op)
            if include_set is not None:
                if op_id not in include_set:
                    continue
            elif op_id in exclude_set:
                continue

            description = (op.get("description") or op.get("summary") or "").strip()
            if not description:
                raise OpenApiRegistrationError(
                    f"operation {op_id!r} ({method.upper()} {path}) has no description or summary — "
                    "every tool registered with Weave must carry one (it's what the model uses to "
                    "decide whether/how to call the tool); add a 'summary' or 'description' to this "
                    "operation in the OpenAPI spec, or exclude it from this registration call"
                )

            planned.append(
                PlannedTool(
                    name=op_id,
                    description=description,
                    endpoint=f"{resolved_base}{path}",
                    method=method.upper(),
                    params_schema=_params_schema(op.get("parameters") or []),
                    visibility=op.get("x-weave-visibility", default_visibility),
                    category=op.get("x-weave-category", default_category),
                    auth_mode=op.get("x-weave-auth-mode", default_auth_mode),
                )
            )
    return planned
